#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OLLAMA_HOST_VALUE="${OLLAMA_HOST:-127.0.0.1:11434}"
GIC_OLLAMA_MODEL="${GIC_OLLAMA_MODEL:-gemma4:e4b-mlx}"
GIC_TTS_BASE_URL="${GIC_TTS_BASE_URL:-http://127.0.0.1:8088}"
GIC_STT_BASE_URL="${GIC_STT_BASE_URL:-http://127.0.0.1:8099}"
GIC_REQUEST_TIMEOUT_SECONDS="${GIC_REQUEST_TIMEOUT_SECONDS:-600}"
GIC_APP_HOST="${GIC_APP_HOST:-127.0.0.1}"
GIC_APP_PORT="${GIC_APP_PORT:-8000}"

cd "$ROOT_DIR/server"

echo "Using Ollama: http://$OLLAMA_HOST_VALUE"
echo "Using model: $GIC_OLLAMA_MODEL"
echo "Using irodori-TTS: $GIC_TTS_BASE_URL"
echo "Using STT: $GIC_STT_BASE_URL"

GIC_OLLAMA_BASE_URL="http://$OLLAMA_HOST_VALUE" \
GIC_OLLAMA_MODEL="$GIC_OLLAMA_MODEL" \
GIC_TTS_BASE_URL="$GIC_TTS_BASE_URL" \
GIC_STT_BASE_URL="$GIC_STT_BASE_URL" \
GIC_REQUEST_TIMEOUT_SECONDS="$GIC_REQUEST_TIMEOUT_SECONDS" \
uv run uvicorn app.main:app --host "$GIC_APP_HOST" --port "$GIC_APP_PORT"
